# SPDX-FileCopyrightText: 2025 Jochim Maene <16223990+JochimMaene@users.noreply.github.com>
#
# SPDX-License-Identifier: MPL-2.0

version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "ccsds-ndm/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore: "
